version: "3.8"

services:
  invoicedb:
    image: mysql:5.7 # Consider using a specific version (e.g., postgres:14)
    platform: linux/amd64
    container_name: invoice-db
    # restart: always
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOTPASSWORD} # Use environment variables for security
      - MYSQL_DATABASE=${DB_MST}
    ports:
      - ${DB_PORT_EXPOSE}:${DB_DEFAULTPORT}
    volumes:
      - invoicedb_data:/var/lib/mysql
      
volumes:
  invoicedb_data:
